### ISSUE TITLE
Consider how state is communicated

### ISSUE THREAD

**Issue by robnagler** [radiasoft/reactapp#5]
In the current implementation, values update across panels as you are typing. This may be suboptimal. I realize this was demonstrating Redux. It does bring up the issue of how state should update. Do we want it to update within a panel in real-time? Inter-panel when you hit enter? Inter-tab when you hit save?

**Comment by garsuga** [comment]
I think this is a non-issue. The performance benefits of more targeted updates here are not worth the increased code complexity. The input components are stateless and derived from the latest form state for the page when any updates are made. This is ideal and it reduces the number of moving parts greatly. Can this be closed?

**Comment by robnagler** [comment]
Does react rerender on every keystroke?

**Comment by robnagler** [comment]
workable solution
