### ISSUE TITLE
Ensure URL structure makes sense and is linkable

### ISSUE THREAD

**Issue by robnagler** [radiasoft/reactapp#7]
Many SPAs don't do this right. We'll want something like `/app#/nagler/srw/source/xyzzy` (currently `/srw#/source/xyzzy`). URL design is important. I think we always want the sim_type in the local (fragment). This is not true now. It may be that we need to add local routes that have a fixed part eg. /u/nagler/srw/source/xyzzy. I would like us to have the user's name in the URL so that we can refer to that user independently of who is logged in. This allows us to authorize access to another user's simulation. I used nagler, but we could just as well use a uid, since we expose the sid's anyway. If we have an appropriate security structure. I also think we should have a regular structure so that we can simplify parsing. This is also true for URLs in the server API.

We'll want to be able to right click on links like the beamline tab vs the source tab. Not all URLs need to be right-clickable, e.g. popups. This needs to be carefully designed, too.

**Comment by e-carlin** [comment]
Another thing to consider is urls for non sim type pages. Like adm-jobs. Currently those have to be tied to a sim type (ex /srw#/adm-jobs) but that shouldn't be the case going forward. 

I think we'll have to use UID (or some other thing we make up for each user). Otherwise we expose PII (ex email or a part of it) correct?

**Comment by robnagler** [comment]
> I think we'll have to use UID (or some other thing we make up for each user). 

We are not exposing PII, because the user is the only one who can see this. If they choose to share it, then they are sharing PII, which is perfectly fine.

**Comment by robnagler** [comment]
I think we may want something like /v1 as the top level url so we can change out apps in the future. /app is too generic.

**Comment by garsuga** [comment]
> I think we may want something like /v1 as the top level url so we can change out apps in the future. /app is too generic.

Can we move to a /api prefix for the API calls as well? This would make the proxy for the front-end much easier

**Comment by garsuga** [comment]
> We'll want to be able to right click on links like the beamline tab vs the source tab. Not all URLs need to be right-clickable, e.g. popups. This needs to be carefully designed, too.

Is this referring to the ability to right click the link on the UI and how would this work on tabs? I think it would not be intuitive for a user to right click a tab to get a link to a section of the page. Instead, how about a 'link icon' like what we see in page headers on Wikipedia? This could be shown on hover perhaps

**Comment by robnagler** [comment]
> Can we move to a /api prefix for the API calls as well? This would make the proxy for the front-end much easier

That's a good idea, and we will eventually. For now, it's too big of a change. The proxy is tricky for dev, but in builds, it won't be needed, since react will be a couple of static files. Eventually, all API calls will go through a websocket so there won't be a need for URLs, and that probably will happen sooner than later.

> Is this referring to the ability to right click the link on the UI and how would this work on tabs? I think it would not be intuitive for a user to right click a tab to get a link to a section of the page. Instead, how about a 'link icon' like what we see in page headers on Wikipedia? This could be shown on hover perhaps

If something looks like a link and not a button, there's a general assumption among non-novice users that you can right click. The tabs in sirepo don't look like tabs and more like links. Indeed along the top nav we have quite a bit of inconsistency which should get cleaned up. I think having them hover underlines like the name of the simulation would be good idea.

In Wikipedia, I don't see what you mean by page headers having a "link icon". I do see that the "tabs" in Wikipedia behave as I would expect: hover underline, right click offers a valid copy link. 

![Screen Shot 2022-08-04 at 11 05 38 AM](https://user-images.githubusercontent.com/5495179/182909529-e30cf34a-55f1-4220-89c7-59a740b96f41.png)

I don't think a link icon is either necessary nor a good idea because it would conflict with other icons.

**Comment by garsuga** [comment]
This has been completed successfully in the JSPEC React application. Is this issue targeted towards the existing Sirepo app as well and can this be closed or should it remain open?

**Comment by robnagler** [comment]
Just React. Seems to work fine.
